#include <stdio.h>
#include <string.h>

#include <openssl/bn.h>
#include <openssl/rand.h>
#include <openssl/err.h>

#define RAND_SIZE 32
#define SEED_SIZE 64

void handle_errors(){
  ERR_print_errors_fp(stderr);
  abort();
}

void print_bytes(unsigned char bytes[], int n) {
  for (int i = 0; i < n; i++)
    printf("%02x", bytes[i]);
  printf("\n");
}

int main() {
  unsigned char rb1[RAND_SIZE];
  unsigned char rb2[RAND_SIZE];
  unsigned char rb3[RAND_SIZE];

  BIGNUM* bn1 = BN_new();
  BIGNUM* bn2 = BN_new();
  BIGNUM* bn3 = BN_new();
  BIGNUM* result = BN_new();

  BN_CTX* ctx = BN_CTX_new();

  // Load OpenSSL facilities
  ERR_load_crypto_strings();

  if(RAND_load_file("/dev/random", SEED_SIZE) != SEED_SIZE)
    handle_errors();

  // Generate 3 random strings
  if(RAND_bytes(rb1, RAND_SIZE) != 1)
    handle_errors();
  if(RAND_bytes(rb2, RAND_SIZE) != 1)
    handle_errors();
  if(RAND_bytes(rb3, RAND_SIZE) != 1)
    handle_errors();

  // Convert the generated bytes to BIGNUMs
  if(BN_bin2bn(rb1, RAND_SIZE, bn1) == NULL)
    handle_errors();
  if(BN_bin2bn(rb2, RAND_SIZE, bn2) == NULL)
    handle_errors();
  if(BN_bin2bn(rb3, RAND_SIZE, bn3) == NULL)
    handle_errors();

  printf("Generated numbers\n");
  printf("BN1: ");
  BN_print_fp(stdout, bn1);
  printf("\nBN2: ");
  BN_print_fp(stdout, bn2);
  printf("\nBN3: ");
  BN_print_fp(stdout, bn3);
  printf("\n\n");

  printf("Operations\n");

  // Addition
  if(!BN_add(result, bn1, bn2))
    handle_errors();
  printf("[+] bn1 + bn2 = ");
  BN_print_fp(stdout, result);
  printf("\n");

  // Substraction
  if(!BN_sub(result, bn1, bn3))
    handle_errors();
  printf("[+] bn1 - bn3 = ");
  BN_print_fp(stdout, result);
  printf("\n");

  // Multiplication
  if(!BN_mul(result, bn1, bn2, ctx))
    handle_errors();
  if(!BN_mul(result, result, bn3, ctx))
    handle_errors();
  printf("[+] bn1 * bn2 * bn3 = ");
  BN_print_fp(stdout, result);
  printf("\n");

  // Division
  BIGNUM* rem = BN_new();
  if(!BN_div(result, rem, bn3, bn1, ctx))
    handle_errors();
  printf("[+] bn3 / bn1 = ");
  BN_print_fp(stdout, result);
  printf(" mod ");
  BN_print_fp(stdout, rem);
  printf("\n");
  BN_free(rem);

  // Modulus
  if(!BN_mod(result, bn1, bn2, ctx))
    handle_errors();
  printf("[+] bn1 mod bn2 = ");
  BN_print_fp(stdout, result);
  printf("\n");

  // Modulus-Exponentiation
  if(!BN_mod_exp(result, bn1, bn3, bn2, ctx))
    handle_errors();
  printf("[+] bn1^bn3 mod bn2 = ");
  BN_print_fp(stdout, result);
  printf("\n");

  // Free all
  BN_free(bn1);
  BN_free(bn2);
  BN_free(bn3);
  BN_free(result);

  BN_CTX_free(ctx);
  CRYPTO_cleanup_all_ex_data();
  ERR_free_strings();
}